# Generated by Django 4.2.7 on 2025-09-28 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_userflashcardprogress_user_profile"),
        ("courses", "0005_make_user_profile_required_in_userflashcardprogress"),
    ]

    operations = []
