# Generated by Django 4.2.7 on 2025-09-28 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0006_merge_20250928_2246"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="subtitles_url",
        ),
        migrations.AddField(
            model_name="lesson",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lesson_audio/",
                verbose_name="Audio-Datei",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Anfänger"),
                    ("intermediate", "Mittelstufe"),
                    ("advanced", "Fortgeschritten"),
                ],
                default="beginner",
                max_length=20,
                verbose_name="Schwierigkeitsgrad",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Dauer (Minuten)"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="grammar_points",
            field=models.TextField(
                blank=True,
                help_text="Grammatikpunkte durch Semikolon getrennt",
                verbose_name="Grammatikpunkte",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Hervorgehoben"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="Kostenlos?"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Kurzbeschreibung"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lesson_thumbnails/",
                verbose_name="Vorschaubild",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="achievements",
            field=models.ManyToManyField(
                blank=True, related_name="user_profiles", to="courses.achievement"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(verbose_name="Inhalt"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.level",
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="URL-Slug"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="translation",
            field=models.TextField(blank=True, verbose_name="Übersetzung"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="vocab",
            field=models.TextField(
                blank=True,
                help_text="Wörter durch Semikolon getrennt",
                verbose_name="Vokabeln",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Unterstützt YouTube-URLs (watch oder embed)",
                verbose_name="YouTube Video URL",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userflashcardprogress",
            unique_together={("user_profile", "flashcard")},
        ),
        migrations.RemoveField(
            model_name="userflashcardprogress",
            name="user",
        ),
    ]
